import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Welcome from "components/Welcome";
import About from "components/AboutUs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Koi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <About />
    </div>
  );
}
